name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            # Fixes https://github.com/expo/expo-github-action/issues/20
            - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - run: corepack enable

            - run: yarn

            - run: yarn build

            - run: yarn test
